export const TOPICS = [
  "Arrays",
  "Strings",
  "Hashing",
  "Two Pointers",
  "Sliding Window",
  "Stack",
  "Queue",
  "Linked List",
  "Trees",
  "Binary Search",
  "Heap",
  "Intervals",
  "Greedy",
  "Backtracking",
  "Dynamic Programming",
  "Graph",
  "Bit Manipulation",
  "Math",
  "Design",
  "Trie",
  "Union Find",
  "Monotonic Stack",
  "Prefix Sum",
  "Matrix",
  "Simulation",
  "Geometry",
  "General",
] as const;

export type Topic = (typeof TOPICS)[number];
